# Generated by Django 4.1.7 on 2023-04-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
